Field:
  x_size: 11
  y_size: 12
  known_area:
    pylon: [[1, 0], [3, 3], [4, 1], [5, 4], [5, 5], [7, 0], [7, 3], [9, 2]]
    box: [[1, 1], [4, 4], [5, 1], [6, 3]]
    storage_space: [[9, 4], [9, 5], [9, 6]]

Barrister:
  i2c_device: /dev/i2c-1
  initial_position: [1, 5]
  initial_angle: 90

ActionPlan:
  - [ [2, 5], false ]
  - [ [2, 4], false ]
  - [ [2, 3], [3, 3] ]
  - [ [2, 2], false ]
  - [ [2, 1], false ]
  - [ [2, 0], [1, 0] ]
  - [ [3, 0], false ]
  - [ [4, 0], [4, 1] ]
  - [ [4, 1], false ]
  - [ [4, 2], false ]
  - [ [4, 3], false ]
  - [ [5, 3], [5, 4] ]
  - [ [5, 4], [5, 5] ]
  - [ [6, 4], false ]
  - [ [7, 4], [7, 3] ]
  - [ [7, 3], false ]
  - [ [7, 2], false ]
  - [ [7, 1], [7, 0] ]
  - [ [8, 1], false ]
  - [ [9, 1], [9, 2] ]
  - [ [9, 2], false ]
  - [ [9, 3], false ]

SlaveAddress:
  driving_right: 0x0A
  driving_left: 0x0B
  sensing: 0x0C
