Field:
  x_size: 11
  y_size: 12
  known_area:
    pylon: [[1, 0], [3, 3], [4, 1], [5, 4], [5, 5], [7, 0], [7, 3], [9, 2]]
    box: [[1, 1], [4, 4], [5, 1], [6, 3]]
  storage_space: [[9, 4], [9, 5], [9, 6]]

Barrister:
  i2c_device: /dev/i2c-1
  initial_position: [1, 6]
  initial_angle: 90

ActionPlan:
  - [[3, 4], true]
  - [[1, 2], false]

SlaveAddress:
  driving_right: 0x0A
  driving_left: 0x0B
  sensing: 0x0C
